package datosEmpre;
// Generated 17 dic 2023 15:31:12 by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas implements java.io.Serializable {

	private long codempre;
	private String nombre;
	private String direccion;
	private String tlf;
	private Double presupuesto;
	private long codsector;
	private long sede;
	private Set departamentoses = new HashSet(0);

	public Empresas() {
	}

	public Empresas(long codempre, String nombre, String direccion, long codsector, long sede) {
		this.codempre = codempre;
		this.nombre = nombre;
		this.direccion = direccion;
		this.codsector = codsector;
		this.sede = sede;
	}

	public Empresas(long codempre, String nombre, String direccion, String tlf, Double presupuesto, long codsector,
			long sede, Set departamentoses) {
		this.codempre = codempre;
		this.nombre = nombre;
		this.direccion = direccion;
		this.tlf = tlf;
		this.presupuesto = presupuesto;
		this.codsector = codsector;
		this.sede = sede;
		this.departamentoses = departamentoses;
	}

	public long getCodempre() {
		return this.codempre;
	}

	public void setCodempre(long codempre) {
		this.codempre = codempre;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTlf() {
		return this.tlf;
	}

	public void setTlf(String tlf) {
		this.tlf = tlf;
	}

	public Double getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(Double presupuesto) {
		this.presupuesto = presupuesto;
	}

	public long getCodsector() {
		return this.codsector;
	}

	public void setCodsector(long codsector) {
		this.codsector = codsector;
	}

	public long getSede() {
		return this.sede;
	}

	public void setSede(long sede) {
		this.sede = sede;
	}

	public Set getDepartamentoses() {
		return this.departamentoses;
	}

	public void setDepartamentoses(Set departamentoses) {
		this.departamentoses = departamentoses;
	}

}
