package datosCicli;
// Generated 18 dic 2023 20:11:39 by Hibernate Tools 5.6.15.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Camisetas generated by hbm2java
 */
public class Camisetas implements java.io.Serializable {

	private BigInteger codigocamiseta;
	private String tipo;
	private String color;
	private BigInteger importepremio;
	private Set resumenCamisetases = new HashSet(0);
	private Set llevas = new HashSet(0);

	public Camisetas() {
	}

	public Camisetas(BigInteger codigocamiseta, String tipo, String color, BigInteger importepremio) {
		this.codigocamiseta = codigocamiseta;
		this.tipo = tipo;
		this.color = color;
		this.importepremio = importepremio;
	}

	public Camisetas(BigInteger codigocamiseta, String tipo, String color, BigInteger importepremio,
			Set resumenCamisetases, Set llevas) {
		this.codigocamiseta = codigocamiseta;
		this.tipo = tipo;
		this.color = color;
		this.importepremio = importepremio;
		this.resumenCamisetases = resumenCamisetases;
		this.llevas = llevas;
	}

	public BigInteger getCodigocamiseta() {
		return this.codigocamiseta;
	}

	public void setCodigocamiseta(BigInteger codigocamiseta) {
		this.codigocamiseta = codigocamiseta;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public BigInteger getImportepremio() {
		return this.importepremio;
	}

	public void setImportepremio(BigInteger importepremio) {
		this.importepremio = importepremio;
	}

	public Set getResumenCamisetases() {
		return this.resumenCamisetases;
	}

	public void setResumenCamisetases(Set resumenCamisetases) {
		this.resumenCamisetases = resumenCamisetases;
	}

	public Set getLlevas() {
		return this.llevas;
	}

	public void setLlevas(Set llevas) {
		this.llevas = llevas;
	}

}
