package clases;
// Generated 20 nov 2023 20:28:47 by Hibernate Tools 6.1.7.Final

import java.math.BigInteger;

/**
 * DetcomprasId generated by hbm2java
 */
public class DetcomprasId implements java.io.Serializable {

	private BigInteger codproducto;
	private BigInteger numcompra;

	public DetcomprasId() {
	}

	public DetcomprasId(BigInteger codproducto, BigInteger numcompra) {
		this.codproducto = codproducto;
		this.numcompra = numcompra;
	}

	public BigInteger getCodproducto() {
		return this.codproducto;
	}

	public void setCodproducto(BigInteger codproducto) {
		this.codproducto = codproducto;
	}

	public BigInteger getNumcompra() {
		return this.numcompra;
	}

	public void setNumcompra(BigInteger numcompra) {
		this.numcompra = numcompra;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetcomprasId))
			return false;
		DetcomprasId castOther = (DetcomprasId) other;

		return ((this.getCodproducto() == castOther.getCodproducto()) || (this.getCodproducto() != null
				&& castOther.getCodproducto() != null && this.getCodproducto().equals(castOther.getCodproducto())))
				&& ((this.getNumcompra() == castOther.getNumcompra()) || (this.getNumcompra() != null
						&& castOther.getNumcompra() != null && this.getNumcompra().equals(castOther.getNumcompra())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodproducto() == null ? 0 : this.getCodproducto().hashCode());
		result = 37 * result + (getNumcompra() == null ? 0 : this.getNumcompra().hashCode());
		return result;
	}

}
