// default package
// Generated 14 dic 2023 22:13:51 by Hibernate Tools 5.6.15.Final

import java.math.BigInteger;
import java.util.Date;

/**
 * T3reservas generated by hbm2java
 */
public class T3reservas implements java.io.Serializable {

	private BigInteger codreserva;
	private T3clientes t3clientes;
	private T3habitaciones t3habitaciones;
	private BigInteger camassupletorias;
	private Date fechaentrada;
	private Date fechasalida;
	private BigInteger descuento;

	public T3reservas() {
	}

	public T3reservas(BigInteger codreserva, T3clientes t3clientes, T3habitaciones t3habitaciones, Date fechaentrada,
			Date fechasalida) {
		this.codreserva = codreserva;
		this.t3clientes = t3clientes;
		this.t3habitaciones = t3habitaciones;
		this.fechaentrada = fechaentrada;
		this.fechasalida = fechasalida;
	}

	public T3reservas(BigInteger codreserva, T3clientes t3clientes, T3habitaciones t3habitaciones,
			BigInteger camassupletorias, Date fechaentrada, Date fechasalida, BigInteger descuento) {
		this.codreserva = codreserva;
		this.t3clientes = t3clientes;
		this.t3habitaciones = t3habitaciones;
		this.camassupletorias = camassupletorias;
		this.fechaentrada = fechaentrada;
		this.fechasalida = fechasalida;
		this.descuento = descuento;
	}

	public BigInteger getCodreserva() {
		return this.codreserva;
	}

	public void setCodreserva(BigInteger codreserva) {
		this.codreserva = codreserva;
	}

	public T3clientes getT3clientes() {
		return this.t3clientes;
	}

	public void setT3clientes(T3clientes t3clientes) {
		this.t3clientes = t3clientes;
	}

	public T3habitaciones getT3habitaciones() {
		return this.t3habitaciones;
	}

	public void setT3habitaciones(T3habitaciones t3habitaciones) {
		this.t3habitaciones = t3habitaciones;
	}

	public BigInteger getCamassupletorias() {
		return this.camassupletorias;
	}

	public void setCamassupletorias(BigInteger camassupletorias) {
		this.camassupletorias = camassupletorias;
	}

	public Date getFechaentrada() {
		return this.fechaentrada;
	}

	public void setFechaentrada(Date fechaentrada) {
		this.fechaentrada = fechaentrada;
	}

	public Date getFechasalida() {
		return this.fechasalida;
	}

	public void setFechasalida(Date fechasalida) {
		this.fechasalida = fechasalida;
	}

	public BigInteger getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigInteger descuento) {
		this.descuento = descuento;
	}

}
