package examen2019;
// Generated 14 dic 2023 15:59:52 by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * T3habitaciones generated by hbm2java
 */
public class T3habitaciones implements java.io.Serializable {

	private String numhabitacion;
	private T3tiposhabitaciones t3tiposhabitaciones;
	private String nombrehabitacion;
	private Set t3reservases = new HashSet(0);

	public T3habitaciones() {
	}

	public T3habitaciones(String numhabitacion) {
		this.numhabitacion = numhabitacion;
	}

	public T3habitaciones(String numhabitacion, T3tiposhabitaciones t3tiposhabitaciones, String nombrehabitacion,
			Set t3reservases) {
		this.numhabitacion = numhabitacion;
		this.t3tiposhabitaciones = t3tiposhabitaciones;
		this.nombrehabitacion = nombrehabitacion;
		this.t3reservases = t3reservases;
	}

	public String getNumhabitacion() {
		return this.numhabitacion;
	}

	public void setNumhabitacion(String numhabitacion) {
		this.numhabitacion = numhabitacion;
	}

	public T3tiposhabitaciones getT3tiposhabitaciones() {
		return this.t3tiposhabitaciones;
	}

	public void setT3tiposhabitaciones(T3tiposhabitaciones t3tiposhabitaciones) {
		this.t3tiposhabitaciones = t3tiposhabitaciones;
	}

	public String getNombrehabitacion() {
		return this.nombrehabitacion;
	}

	public void setNombrehabitacion(String nombrehabitacion) {
		this.nombrehabitacion = nombrehabitacion;
	}

	public Set getT3reservases() {
		return this.t3reservases;
	}

	public void setT3reservases(Set t3reservases) {
		this.t3reservases = t3reservases;
	}

}
