package examen2019;
// Generated 14 dic 2023 15:59:52 by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * T3tiposhabitaciones generated by hbm2java
 */
public class T3tiposhabitaciones implements java.io.Serializable {

	private String tipo;
	private String descripciontexto;
	private double precio;
	private Set t3habitacioneses = new HashSet(0);

	public T3tiposhabitaciones() {
	}

	public T3tiposhabitaciones(String tipo, double precio) {
		this.tipo = tipo;
		this.precio = precio;
	}

	public T3tiposhabitaciones(String tipo, String descripciontexto, double precio, Set t3habitacioneses) {
		this.tipo = tipo;
		this.descripciontexto = descripciontexto;
		this.precio = precio;
		this.t3habitacioneses = t3habitacioneses;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getDescripciontexto() {
		return this.descripciontexto;
	}

	public void setDescripciontexto(String descripciontexto) {
		this.descripciontexto = descripciontexto;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public Set getT3habitacioneses() {
		return this.t3habitacioneses;
	}

	public void setT3habitacioneses(Set t3habitacioneses) {
		this.t3habitacioneses = t3habitacioneses;
	}

}
